### ISSUE TITLE
30 tests fail on nodejs 10.8

### ISSUE THREAD

**Issue by simevo** [isaacs/chownr#16]
```
# uname -a
Linux teamdigitale1 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
# nodejs -v
v10.8.0
# yarnpkg -v
1.9.4
# yarnpkg install
yarn install v1.9.4
info No lockfile found.
[1/4] Resolving packages...
warning tap > nyc > istanbul > fileset > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[2/4] Fetching packages...
[------------------------------------------------------------------------------------] 0/187(node:14350) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 8.39s.
# 
# node_modules/tap/bin/run.js -Rspec test/*.js

test/basic.js
  should complete successfully
    1) TypeError [ERR_INVALID_ARG_TYPE]: The "gid" argument must be of type number. Received type undefined                                                                               

  verify /tmp/chownr/c88d
    ✓ uid should be 0
    2) gid should be undefined

  verify /tmp/chownr/c88d/516b
    ✓ uid should be 0
    3) gid should be undefined

  verify /tmp/chownr/c88d/516b/b350
    ✓ uid should be 0
    4) gid should be undefined

  verify /tmp/chownr/24f7
    ✓ uid should be 0
    5) gid should be undefined

  verify /tmp/chownr/24f7/1ef1
    ✓ uid should be 0
    6) gid should be undefined

  verify /tmp/chownr/24f7/1ef1/2ed0
    ✓ uid should be 0
    7) gid should be undefined

  verify /tmp/chownr/450f
    ✓ uid should be 0
    8) gid should be undefined

  verify /tmp/chownr/450f/948b
    ✓ uid should be 0
    9) gid should be undefined

  verify /tmp/chownr/450f/948b/b30f
    ✓ uid should be 0
    10) gid should be undefined

  verify /tmp/chownr/6a7d
    ✓ uid should be 0
    11) gid should be undefined

  verify /tmp/chownr/6a7d/6e3b
    ✓ uid should be 0
    12) gid should be undefined

  verify /tmp/chownr/6a7d/6e3b/63f8
    ✓ uid should be 0
    13) gid should be undefined

  verify /tmp/chownr/9ec
    ✓ uid should be 0
    14) gid should be undefined

  verify /tmp/chownr/9ec/a4fb
    ✓ uid should be 0
    15) gid should be undefined

  verify /tmp/chownr/9ec/a4fb/7663
    ✓ uid should be 0
    16) gid should be undefined

  cleanup
    ✓ should not error

  17) TypeError [ERR_INVALID_ARG_TYPE]: The "gid" argument must be of type number. Received type undefined                                                                                
  18) TypeError [ERR_INVALID_ARG_TYPE]: The "gid" argument must be of type number. Received type undefined                                                                                
  19) TypeError [ERR_INVALID_ARG_TYPE]: The "gid" argument must be of type number. Received type undefined                                                                                
  20) TypeError [ERR_INVALID_ARG_TYPE]: The "gid" argument must be of type number. Received type undefined                                                                                
test/symlink.js
  should complete successfully
    21) TypeError [ERR_INVALID_ARG_TYPE]: The "gid" argument must be of type number. Received type undefined                                                                              

  verify sh-link
    22) uid not should be 0
    ✓ gid not should be undefined

  cleanup
    ✓ should not error

test/symlink-sync.js
  should complete successfully
    23) TypeError [ERR_INVALID_ARG_TYPE]: The "gid" argument must be of type number. Received type undefined                                                                              

(node:14400) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
  verify sh-link
    24) uid not should be 0
    ✓ gid not should be undefined

  cleanup
    ✓ should not error

test/sync.js
  should complete successfully
    25) TypeError [ERR_INVALID_ARG_TYPE]: The "gid" argument must be of type number. Received type undefined                                                                              

(node:14412) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
  verify /tmp/chownr/e9ac/3dc6/373a
    ✓ uid should be 0
    26) gid should be undefined

  verify /tmp/chownr/5f89/73ab/e09f
    ✓ uid should be 0
    27) gid should be undefined

  verify /tmp/chownr/9dfe/5ced/4be1
    ✓ uid should be 0
    28) gid should be undefined

  verify /tmp/chownr/dc57/57ab/676b
    ✓ uid should be 0
    29) gid should be undefined

  verify /tmp/chownr/b675/5ead/b9f9
    ✓ uid should be 0
    30) gid should be undefined

  cleanup
    ✓ should not error


  26 passing (1s)
  30 failing

  1) test/basic.js should complete successfully TypeError [ERR_INVALID_ARG_TYPE]: The "gid" argument must be of type number. Received type undefined:
     Error: TypeError [ERR_INVALID_ARG_TYPE]: The "gid" argument must be of type number. Received type undefined                                                                          
      at Object.chown (fs.js:1036:3)                                                         
      at chownr.js:12:43                                                                     
      at FSReqWrap.oncomplete (fs.js:139:20)                                                 

  2) test/basic.js verify /tmp/chownr/c88d gid should be undefined:
     Error: gid should be undefined
      at test/basic.js:72:11                                                                 
      at FSReqWrap.oncomplete (fs.js:153:5)                                                  

  3) test/basic.js verify /tmp/chownr/c88d/516b gid should be undefined:
     Error: gid should be undefined
      at test/basic.js:72:11                                                                 
      at FSReqWrap.oncomplete (fs.js:153:5)                                                  

  4) test/basic.js verify /tmp/chownr/c88d/516b/b350 gid should be undefined:
     Error: gid should be undefined
      at test/basic.js:72:11                                                                 
      at FSReqWrap.oncomplete (fs.js:153:5)                                                  

  5) test/basic.js verify /tmp/chownr/24f7 gid should be undefined:
     Error: gid should be undefined
      at test/basic.js:72:11                                                                 
      at FSReqWrap.oncomplete (fs.js:153:5)                                                  

  6) test/basic.js verify /tmp/chownr/24f7/1ef1 gid should be undefined:
     Error: gid should be undefined
      at test/basic.js:72:11                                                                 
      at FSReqWrap.oncomplete (fs.js:153:5)                                                  

  7) test/basic.js verify /tmp/chownr/24f7/1ef1/2ed0 gid should be undefined:
     Error: gid should be undefined
      at test/basic.js:72:11                                                                 
      at FSReqWrap.oncomplete (fs.js:153:5)                                                  

  8) test/basic.js verify /tmp/chownr/450f gid should be undefined:
     Error: gid should be undefined
      at test/basic.js:72:11                                                                 
      at FSReqWrap.oncomplete (fs.js:153:5)                                                  

  9) test/basic.js verify /tmp/chownr/450f/948b gid should be undefined:
     Error: gid should be undefined
      at test/basic.js:72:11                                                                 
      at FSReqWrap.oncomplete (fs.js:153:5)                                                  

  10) test/basic.js verify /tmp/chownr/450f/948b/b30f gid should be undefined:
     Error: gid should be undefined
      at test/basic.js:72:11                                                                 
      at FSReqWrap.oncomplete (fs.js:153:5)                                                  

  11) test/basic.js verify /tmp/chownr/6a7d gid should be undefined:
     Error: gid should be undefined
      at test/basic.js:72:11                                                                 
      at FSReqWrap.oncomplete (fs.js:153:5)                                                  

  12) test/basic.js verify /tmp/chownr/6a7d/6e3b gid should be undefined:
     Error: gid should be undefined
      at test/basic.js:72:11                                                                 
      at FSReqWrap.oncomplete (fs.js:153:5)                                                  

  13) test/basic.js verify /tmp/chownr/6a7d/6e3b/63f8 gid should be undefined:
     Error: gid should be undefined
      at test/basic.js:72:11                                                                 
      at FSReqWrap.oncomplete (fs.js:153:5)                                                  

  14) test/basic.js verify /tmp/chownr/9ec gid should be undefined:
     Error: gid should be undefined
      at test/basic.js:72:11                                                                 
      at FSReqWrap.oncomplete (fs.js:153:5)                                                  

  15) test/basic.js verify /tmp/chownr/9ec/a4fb gid should be undefined:
     Error: gid should be undefined
      at test/basic.js:72:11                                                                 
      at FSReqWrap.oncomplete (fs.js:153:5)                                                  

  16) test/basic.js verify /tmp/chownr/9ec/a4fb/7663 gid should be undefined:
     Error: gid should be undefined
      at test/basic.js:72:11                                                                 
      at FSReqWrap.oncomplete (fs.js:153:5)                                                  

  17) test/basic.js TypeError [ERR_INVALID_ARG_TYPE]: The "gid" argument must be of type number. Received type undefined:
     Error: TypeError [ERR_INVALID_ARG_TYPE]: The "gid" argument must be of type number. Received type undefined                                                                          
      at Object.chown (fs.js:1036:3)                                                         
      at chownr.js:12:43                                                                     
      at FSReqWrap.oncomplete (fs.js:139:20)                                                 

  18) test/basic.js TypeError [ERR_INVALID_ARG_TYPE]: The "gid" argument must be of type number. Received type undefined:
     Error: TypeError [ERR_INVALID_ARG_TYPE]: The "gid" argument must be of type number. Received type undefined                                                                          
      at Object.chown (fs.js:1036:3)                                                         
      at chownr.js:12:43                                                                     
      at FSReqWrap.oncomplete (fs.js:139:20)                                                 

  19) test/basic.js TypeError [ERR_INVALID_ARG_TYPE]: The "gid" argument must be of type number. Received type undefined:
     Error: TypeError [ERR_INVALID_ARG_TYPE]: The "gid" argument must be of type number. Received type undefined                                                                          
      at Object.chown (fs.js:1036:3)                                                         
      at chownr.js:12:43                                                                     
      at FSReqWrap.oncomplete (fs.js:139:20)                                                 

  20) test/basic.js TypeError [ERR_INVALID_ARG_TYPE]: The "gid" argument must be of type number. Received type undefined:
     Error: TypeError [ERR_INVALID_ARG_TYPE]: The "gid" argument must be of type number. Received type undefined                                                                          
      at Object.chown (fs.js:1036:3)                                                         
      at chownr.js:12:43                                                                     
      at FSReqWrap.oncomplete (fs.js:139:20)                                                 

  21) test/symlink.js should complete successfully TypeError [ERR_INVALID_ARG_TYPE]: The "gid" argument must be of type number. Received type undefined:
     Error: TypeError [ERR_INVALID_ARG_TYPE]: The "gid" argument must be of type number. Received type undefined                                                                          
      at Object.chown (fs.js:1036:3)                                                         
      at then (chownr.js:30:35)                                                              
      at chownr.js:24:11                                                                     
      at FSReqWrap.oncomplete (fs.js:153:5)                                                  

  22) test/symlink.js verify sh-link uid not should be 0:
     Error: uid not should be 0
      at test/symlink.js:51:9                                                                
      at FSReqWrap.oncomplete (fs.js:153:5)                                                  

  23) test/symlink-sync.js should complete successfully TypeError [ERR_INVALID_ARG_TYPE]: The "gid" argument must be of type number. Received type undefined:
     Error: TypeError [ERR_INVALID_ARG_TYPE]: The "gid" argument must be of type number. Received type undefined                                                                          
      at Object.chownSync (fs.js:1047:3)                                                     
      at Function.chownrSync [as sync] (chownr.js:51:13)                                     
      at test/symlink-sync.js:38:12                                                          
      at runTest (test/symlink-sync.js:36:3)                                                 
      at test/symlink-sync.js:31:5                                                           

  24) test/symlink-sync.js verify sh-link uid not should be 0:
     Error: uid not should be 0
      at test/symlink-sync.js:48:9                                                           
      at FSReqWrap.oncomplete (fs.js:153:5)                                                  

  25) test/sync.js should complete successfully TypeError [ERR_INVALID_ARG_TYPE]: The "gid" argument must be of type number. Received type undefined:
     Error: TypeError [ERR_INVALID_ARG_TYPE]: The "gid" argument must be of type number. Received type undefined                                                                          
      at Object.chownSync (fs.js:1047:3)                                                     
      at chownrSync (chownr.js:43:35)
      at chownr.js:49:7
      at Array.forEach (<anonymous>)
      at chownrSync (chownr.js:45:12)
      at chownr.js:49:7
      at Array.forEach (<anonymous>)
      at chownrSync (chownr.js:45:12)
      at chownr.js:49:7
      at Array.forEach (<anonymous>)

  26) test/sync.js verify /tmp/chownr/e9ac/3dc6/373a gid should be undefined:
     Error: gid should be undefined
      at test/sync.js:67:11
      at FSReqWrap.oncomplete (fs.js:153:5)

  27) test/sync.js verify /tmp/chownr/5f89/73ab/e09f gid should be undefined:
     Error: gid should be undefined
      at test/sync.js:67:11
      at FSReqWrap.oncomplete (fs.js:153:5)

  28) test/sync.js verify /tmp/chownr/9dfe/5ced/4be1 gid should be undefined:
     Error: gid should be undefined
      at test/sync.js:67:11
      at FSReqWrap.oncomplete (fs.js:153:5)

  29) test/sync.js verify /tmp/chownr/dc57/57ab/676b gid should be undefined:
     Error: gid should be undefined
      at test/sync.js:67:11
      at FSReqWrap.oncomplete (fs.js:153:5)

  30) test/sync.js verify /tmp/chownr/b675/5ead/b9f9 gid should be undefined:
     Error: gid should be undefined
      at test/sync.js:67:11
      at FSReqWrap.oncomplete (fs.js:153:5)
```

**Comment by EightArmCode** [comment]
I am trying to get this running locally to see if I can help debug the tests, but running into a lot of problems just trying to install

**Comment by isaacs** [comment]
Tests work for me on 10.8.

```
.isaacs/chownr geegaw:~/dev/js/chownr node@10.8.0
$ nt

> chownr@1.1.1 test /Users/isaacs/dev/js/chownr
> tap test/*.js --cov

test/basic.js ....................................... 32/32
test/old-readdir-sync.js ............................ 12/12
test/old-readdir.js ................................. 32/32
test/symlink-sync.js .................................. 4/4
test/symlink.js ....................................... 4/4
test/sync.js ........................................ 12/12
total ............................................... 96/96

  96 passing (4s)

  ok
-----------|----------|----------|----------|----------|-------------------|
File       |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-----------|----------|----------|----------|----------|-------------------|
All files  |    85.96 |    61.76 |      100 |    87.76 |                   |
 chownr.js |    85.96 |    61.76 |      100 |    87.76 | 22,30,43,76,77,78 |
-----------|----------|----------|----------|----------|-------------------|
```
